[package]
name = "rue-landing"
version.workspace = true
description = "Landing page example for Rue framework"
publish = false
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rue-core = { path = "../../core" }
rue-macros = { path = "../../macros" }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = [
    "Event",
    "MouseEvent",
] }
console_error_panic_hook = { workspace = true }
